### ISSUE TITLE
commonjs build does not work from a script tag

### ISSUE THREAD

**Issue by dustingetz** [dustingetz/react-cursor#50]
The production file needs to detect when it is used from a script tag (instead of a module loader) and export `window.Cursor` global.

**Comment by dustingetz** [comment]
https://github.com/dustingetz/react-cursor/pull/3

**Comment by dustingetz** [comment]
@damassi do you know how to fix this quickly?

**Comment by damassi** [comment]
Sure, I can take care of it in about an hour, when I get into the office

**Comment by dustingetz** [comment]
Thanks. Here is my attempt, in which react-cursor throws "Uncaught Error: Cannot find module 'react/addons'"

https://github.com/dustingetz/react-cursor/compare/djg/fix-standalone

**Comment by dustingetz** [comment]
I think what I missed is that react needs to be shimmed

**Comment by damassi** [comment]
ah cool, so you got it?

**Comment by damassi** [comment]
either way, i'm about to commit a PR that swaps out browserify for webpack that simplifies things quite substantially and exports a UMD target.

**Comment by dustingetz** [comment]
Not resolved yet - yes, please for the PR - thank you so much!

**Comment by damassi** [comment]
np

**Comment by damassi** [comment]
Ok, @dustingetz -- be prepared for a big PR.  I replaced browserify and grunt with webpack, cleaned up your test structure and karma configuration, cleaned up the example structure and moved each over to webpack-hot-reloader so that users can take advantage when experimenting, and generally just simplified overall.  I'll write a more thorough overview in the PR, but don't want to surprise you when you get the request!

**Comment by dustingetz** [comment]
Hit me. You're the man Christopher, thanks!

**Comment by damassi** [comment]
See https://github.com/dustingetz/react-cursor/pull/52
